// Generates src/version.ts by reading the current package.json version and
// emitting it as a TypeScript string constant.
//
// Why codegen instead of importing package.json directly: this package
// builds to both CJS and ESM. CJS `require('../package.json')` works
// natively, but ESM (Node >= 22) requires
// `import pkg from '../package.json' with { type: 'json' }`, and
// TypeScript cannot conditionally emit that attribute for a dual build.
// Inlining the version as a TS constant sidesteps the issue entirely and
// matches the pattern already used for the hosted-tools manifest.
//
// The generated file is .gitignored. Run via `npm run build` (via the
// pre-build script) or explicitly via `npm run codegen`.
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(here, '..', 'package.json');
const outFile = join(here, '..', 'src', 'version.ts');

const pkg = JSON.parse(await readFile(pkgPath, 'utf8'));

const banner = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit.\n// Source of truth: package.json version.\n`;
const body = `export const LIB_VERSION = '${pkg.version}';\n`;
await writeFile(outFile, banner + body, 'utf8');

console.log(`[generate-version] wrote ${outFile} = ${pkg.version}`);
